# Generated by Django 5.0.4 on 2024-08-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_remove_labreport_test_name_test_labreport_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labreport',
            old_name='test',
            new_name='test_name',
        ),
    ]
