# Generated by Django 5.0.4 on 2024-08-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_zoomtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomtoken',
            name='access_token',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='zoomtoken',
            name='refresh_token',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
