# Generated by Django 5.0.4 on 2024-08-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_alter_zoomtoken_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomtoken',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='zoomtoken',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
    ]
