# Generated by Django 5.0.4 on 2024-08-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_alter_zoomtoken_access_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='zoom_join_link',
            new_name='join_link',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='zoom_meeting_id',
            new_name='meeting_id',
        ),
    ]
