# Generated by Django 5.0.4 on 2024-08-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_rename_zoom_join_link_appointment_join_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
